### ISSUE TITLE
Cannot build typescript files with nestjs-telegraf 

### ISSUE THREAD

**Issue by oneassasin** [nksmnf/nestjs-telegraf#362]
Screenshot: http://joxi.ru/Dr8ORkjcMgJdzA

**Comment by evilsprut** [comment]
Looks like is not a `nestjs-telegraf` error. Can you give more context?

**Comment by oneassasin** [comment]
http://joxi.ru/l2ZQ4yEU7xgpPm
incorrect code from types

```
import { Composer, Middleware } from 'telegraf';
export declare type Filter<T extends any[], F> = T extends [] ? [] : T extends [infer Head, ...infer Tail] ? Head extends F ? Filter<Tail, F> : [Head, ...Filter<Tail, F>] : [];
export declare type OnlyFunctionPropertyNames<T> = {
    [K in keyof T]: T[K] extends (...args: any) => any ? K : never;
}[keyof T];
export declare type ComposerMethodArgs<T extends Composer<never>, U extends OnlyFunctionPropertyNames<T> = OnlyFunctionPropertyNames<T>> = Filter<Parameters<T[U]>, Middleware<never>>;
```

**Comment by evilsprut** [comment]
> http://joxi.ru/l2ZQ4yEU7xgpPm
> incorrect code from types

Hey, @oneassasin is not a incorrect code. `typescript` package version in your project doesn't support this syntax. Minimal required TypeScript version for that - `4.1.2`. I also released a new version (`2.2.3`) of the package where I specified the supported TypeScript version in `peerDependencies` (https://github.com/bukhalo/nestjs-telegraf/commit/a1f441ff740bca5d144f86db94784a48be843300) . Thanks for the info!

**Comment by evilsprut** [comment]
https://github.com/telegraf/telegraf/issues/1411

**Comment by MufassirShaw** [comment]
Hello @bukhalo, thanks a lot for the package. 
Apparently this issue seems to have comeback in the latest versions. I'm using 

nestjs-telegraf: `^2.4.0`,
telegraf: `^4.5.2`
typescript: `^4.3.5`

Here is what I see as soon as I import anything from `nestjs-telegraf`

![image](https://user-images.githubusercontent.com/30889549/147561214-3015d272-221d-4e2c-9e66-77d495e926ad.png)

Thanks

**Comment by AidarNurakov** [comment]
Hello my friend, have you solved that trouble already?

**Comment by aidarnurakov** [comment]
Hello @MufassirShaw  have you solved that issue already?

**Comment by MufassirShaw** [comment]
Hi @AidarNurakov. 

I couldn't find a way around this issue in the latest package. Only downgrading the package version worked for me. 

Here are the version i'm using. 

nestjs-telegraf" `2.4.0`,
telegraf": `4.4.2`,
typescript: `4.4.4`

You may use these exact versions for now and upgrade it once the issue is fixed. 

I hope this helps :)

**Comment by evilsprut** [comment]
Hey dudes. Yes, there is a problem. I noticed it when the [typescript update](https://github.com/bukhalo/nestjs-telegraf/pull/759) came in. As far as I understood the last working version of typescript is `4.4.4`. I will try to solve the problem in the near future.
